import { Link } from 'react-router-dom'
import styles from './Legal.module.css'

export default function Terms() {
  return (
    <div className={styles.page}>
      <div className={styles.card}>
        <Link to="/" className={styles.back}>← Back to Mediant</Link>
        <h1 className={styles.title}>Terms of Service</h1>
        <p className={styles.updated}>Last updated: May 2025</p>

        <section className={styles.section}>
          <h2>Using Mediant</h2>
          <p>By creating an account you agree to use Mediant only for lawful purposes. You must be at least 13 years old. You are responsible for keeping your login credentials secure.</p>
        </section>

        <section className={styles.section}>
          <h2>Your content</h2>
          <p>You own all recordings and sheet music you upload. By uploading, you grant Mediant a limited licence to process that content solely for the purpose of generating your performance analysis. We do not share your recordings with other users.</p>
        </section>

        <section className={styles.section}>
          <h2>Analysis accuracy</h2>
          <p>Mediant's feedback is generated by AI and is intended as a practice aid, not a substitute for a professional music teacher. Measure numbers and technical assessments may occasionally be inaccurate. Always use your own judgement alongside Mediant's feedback.</p>
        </section>

        <section className={styles.section}>
          <h2>Free and Pro plans</h2>
          <p>Free accounts may run up to 10 analyses per day. Pro accounts have no daily limit. Subscription fees are billed monthly and are non-refundable except where required by law. You may cancel at any time — your Pro access continues until the end of the billing period.</p>
        </section>

        <section className={styles.section}>
          <h2>Acceptable use</h2>
          <p>You may not use Mediant to upload content that infringes copyright, contains illegal material, or is intended to harm others. We reserve the right to suspend accounts that violate these terms.</p>
        </section>

        <section className={styles.section}>
          <h2>Service availability</h2>
          <p>We aim for high availability but do not guarantee uninterrupted service. We are not liable for any losses arising from downtime or inaccurate analysis output.</p>
        </section>

        <section className={styles.section}>
          <h2>Changes to these terms</h2>
          <p>We may update these terms from time to time. We'll notify you by email if the changes are significant. Continued use of Mediant after changes means you accept the updated terms.</p>
        </section>

        <section className={styles.section}>
          <h2>Contact</h2>
          <p>Questions? Email <a href="mailto:hello@mediant.app">hello@mediant.app</a>.</p>
        </section>
      </div>
    </div>
  )
}
