import { Link } from 'react-router-dom'
import styles from './Legal.module.css'

export default function Terms() {
  return (
    <div className={styles.page}>
      <div className={styles.card}>
        <Link to="/" className={styles.back}>← Back to Mediant</Link>
        <h1 className={styles.title}>Terms of Service</h1>
        <p className={styles.updated}>Last updated: June 2026</p>

        <section className={styles.section}>
          <h2>Using Mediant</h2>
          <p>By creating an account you agree to use Mediant only for lawful purposes. You must be at least 13 years old to create an account. You are responsible for keeping your login credentials secure and for all activity that occurs under your account.</p>
        </section>

        <section className={styles.section}>
          <h2>Your content</h2>
          <p>You own all recordings and sheet music you upload. By uploading, you grant Mediant a limited, non-exclusive licence to process that content solely for the purpose of generating your performance analysis and displaying it back to you. We do not share your recordings with other users. We do not use your recordings to train AI models.</p>
        </section>

        <section className={styles.section}>
          <h2>Analysis accuracy</h2>
          <p>Mediant's feedback is generated by AI and is intended as a practice aid, not a substitute for a professional music teacher. Measure numbers, pitch assessments, and technical observations may occasionally be inaccurate. Always use your own judgement alongside Mediant's feedback.</p>
        </section>

        <section className={styles.section}>
          <h2>Free and Pro plans</h2>
          <p>Free accounts include one complimentary analysis. Pro accounts have no analysis limit. Subscription fees are billed monthly and are non-refundable except where required by applicable law. You may cancel at any time from your account settings — your Pro access continues until the end of the current billing period.</p>
        </section>

        <section className={styles.section}>
          <h2>Acceptable use</h2>
          <p>You may not use Mediant to upload content that infringes copyright, contains illegal material, or is intended to harm others. Video uploads are limited to 200 MB and 20 minutes per recording. We reserve the right to suspend or terminate accounts that violate these terms without prior notice.</p>
        </section>

        <section className={styles.section}>
          <h2>Service availability</h2>
          <p>We aim for high availability but do not guarantee uninterrupted service. Analysis processing times may vary depending on server load. We are not liable for any losses arising from downtime, processing delays, or inaccurate analysis output.</p>
        </section>

        <section className={styles.section}>
          <h2>Limitation of liability</h2>
          <p>To the maximum extent permitted by law, Mediant is provided "as is" without warranty of any kind. We are not liable for indirect, incidental, or consequential damages arising from your use of the service.</p>
        </section>

        <section className={styles.section}>
          <h2>Changes to these terms</h2>
          <p>We may update these terms from time to time. We will notify you by email if the changes are significant. Continued use of Mediant after changes take effect means you accept the updated terms.</p>
        </section>

        <section className={styles.section}>
          <h2>Governing law</h2>
          <p>These terms are governed by the laws of the jurisdiction in which Mediant operates. Any disputes will be resolved in the courts of that jurisdiction.</p>
        </section>

        <section className={styles.section}>
          <h2>Contact</h2>
          <p>Questions? Email <a href="mailto:mediantteam@gmail.com">mediantteam@gmail.com</a>.</p>
        </section>
      </div>
    </div>
  )
}
